if(MSVC)
	set(CMAKE_CXX_FLAGS_DEBUG_INIT          "/Zi /MT /WX- /0d /EHsc /GS- /Oy- /Oi /Ot /Oy /arch:SSE2 /fp:precise /D_DEBUG /D _WINDLL")
	set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT         "/MT /WX- /O1 /EHsc /GS- /Oy  /Oi /Ot /Oy /arch:SSE2 /fp:precise /D NDEBUG")
	set(CMAKE_CXX_FLAGS_RELEASE_INIT            "/MT /WX- /O2 /EHsc /GS- /Oy  /Oi /Ot /Oy /arch:SSE2 /fp:precise /D NDEBUG")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/Zi /MT /Zi  /O2 /EHsc /GS- /Oy- /Oi /Ot /Oy /arch:SSE2 /fp:precise /D_DEBUG")
else()
	set(CMAKE_CXX_FLAGS_DEBUG_INIT 			  "-std=c++11 -march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
	set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT       "-std=c++11 -march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
	set(CMAKE_CXX_FLAGS_RELEASE_INIT          "-std=c++11 -march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT   "-std=c++11 -march=i686 -msse2 -msse3 -fPIC -m32 -O2 -fomit-frame-pointer")
endif()